language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo generate


after_success:
  - "find public -type f -exec curl -u ${AZURE_WA_USERNAME}:${AZURE_WA_PASSWORD} --ftp-create-dirs -T {} ${AZURE_WA_SITE}/site/wwwroot/{} \\;"
  
 
