language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo g
  
after_script:
  - cd
  - cd ./public
  - git init
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${AZURE_WA_USERNAME}:${AZURE_WA_PASSWORD}@${AZURE_WA_SITE}/ngbeijing.git" master:master
