language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo g
  - git push --force --quiet "https://ngbeijing.scm.azurewebsites.net:443/ngbeijing.git" master:master
