language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo generate

after_success:
  - git remote add azure https://${AZURE_WA_USERNAME}:${AZURE_WA_PASSWORD}@ngbeijing.scm.azurewebsites.net:443/ngbeijing.git/
  - git pull
  - git push azure master
